---
title: "Computational Programming with Python"
format: html
filters:
  - pyodide
resources:
  - MonaLisa.jpg
---

## Lecture 7: More on arrays, more on functions


### Center for Mathematical Sciences, Lund University
Lecturer: Malin Christersson, `Robert Klöfkorn`

<a class="lecture-download-link" href="original_files/lecture07.ipynb?download=1" download>Download original notebook (.ipynb)</a>

## This lecture

- Showing more than one plot
- More about numpy arrays
- Boolean arrays
- Universal functions
- Images as matrices

# Showing more than one plot

Using `matplotlib.pyplot`, we can show many plots arranged in a grid using the command

```python
subplot(RowsColumnsPlotnumber)
```

where the argument is given as three consecutive numbers, e.g. `subplot(211)` (2 rows, 1 column, plot nr 1).

#### The imports needed

```{pyodide-python}
from numpy import *
from matplotlib.pyplot import *

```

### Using 2 rows, 1 column

```{pyodide-python}
x = linspace(-2*pi, 2*pi, 100)
figure(figsize=(8, 4))
subplot(211) # also possible subplot(2,1,1)                
plot(x, sin(x), label="sin(x)"); legend()
subplot(212) # again, also possible subplot(2,1,2)
plot(x, sin(2*x), label="sin(2*x)")
xlabel('x')
legend()
```

## Using 1 row, 2 columns

```{pyodide-python}
x = linspace(-2*pi, 2*pi, 100)
figure(figsize=(12, 2))
subplot(121) # also possible subplot(1,2,1)               
plot(x, sin(x), label="sin(x)"); legend()
subplot(122) # also possible subplot(1,2,2)
plot(x, sin(2*x), label="sin(2*x)"); legend()
```

## Using 2 rows, 3 columns

```{pyodide-python}
x = linspace(-2*pi, 2*pi, 100)
figure(figsize=(12, 4)) # width and height in inches
subplot(231)            
plot(x, sin(x), label="sin(x)")
ylabel("sin(x)")
subplot(232)
plot(x, sin(2*x), label="sin(2*x)"); legend(loc='upper left')
ylabel("sin(x)")
subplot(233)
plot(x, sin(3*x))
subplot(234)                
plot(x, x)
subplot(235)
plot(x, x**2)
subplot(236)
plot(x, x**3)
tight_layout()
```

# More about numpy arrays

We can compare the built-in function `range`  with the `numpy` functions `linspace` and `arange`.

```python
range(start, stop, step)  # only integers, stop not included
linspace(start, stop, number_of_points)  # stop included
arange(start, stop, step)                # stop not included
```

```{pyodide-python}
x1 = arange(0, 10, 2)
print(x1)
print(type(x1[0]))

x2 = arange(0., 10, 2)  # one dot to make floats
print(x2)
print(type(x2[0]))

x3 = arange(0, 3, 0.5)  
print(x3)
```


## Solving simultanous linear equations

If $A$ is a matrix and $b$ is a vector, you solve the linear equation
$$A\cdot x = b$$
using `solve`, which has the syntax `x=solve(A, b)`.

### Example

We want to solve

$$ 
\begin{cases}
x_1 + 2x_2 &= 1\\
3x_1 + 4x_2 &= 4
\end{cases}
$$

```{pyodide-python}
from numpy import *
from scipy.linalg import solve

A = array([[1., 2.], 
           [3., 4.]])
b = array([1., 4.])
x = solve(A,b)
print("x =", x)
print(dot(A, x))     # should be almost b
```


## Slices
Slices are similar to that of lists and vectors **except** that there are now **two dimensions**.

`M[i,:]` a vector filled by the row $i$ of $M$.

`M[:,j]` a vector filled by the column $j$ of $M$.

`M[2:4,:]` slice 2:4 on the rows only

`M[2:4,1:4]`slice on rows and columns

## Slices &hyphen; omitting a dimension

If you omit an index, Numpy assumes you are taking rows only.

`M[3]` is the forth row of $M$

`M[1:3]` is a matrix with the second and third rows of $M$

### Slices, examples

```{pyodide-python}
M = array([[1,   2,   3,   4  ],
           [10,  20,  30,  40 ],
           [100, 200, 300, 400]])

print(M[2,:],"\n")      # row 2
print(M[:,2],"\n")      # column 2

print(M[:, 1:3],"\n")   # slice on columns

print(M[0:2])           # omitting a dimension
```

## Some technical terms

There are three *attributes* `ndim`, `shape` and `size` that can be used on an array.

```{pyodide-python}
M = array([[1,   2,   3,   4  ],
           [10,  20,  30,  40 ],
           [100, 200, 300, 400]])

print("dimension = ", M.ndim)  # the tensor dimension
print("shape = ", M.shape)     # M is a 3 times 4 matrix
print("size =", M.size)        # the total number of elements
```


## Dimensions of matrix slices

| access | ndim | kind | example |
|:---- | :---: | :--- | :--- |
|index, index | 0 | scalar | `M[2, 0]` |
|slice,index | 1 | vector | `M[1, :]` |
|slice, slice| 2 | matrix | `M[0:2, 2:3]` |

#### Example 1

Make a slice for the red elements. What is the dimension of the slice?
$$
M = 
\begin{pmatrix}
0 & \color{red}{\begin{matrix} 1 & 2 & 3 \end{matrix}} \\
4 & \color{red}{\begin{matrix} 5 & 6 & 7 \end{matrix}} \\
8 & \begin{matrix} 9 & 10 & 11 \end{matrix}
\end{pmatrix}
$$

#### Example 2

Make a slice for the red elements. What is the dimension of the slice?
$$
M = 
\begin{pmatrix}
0 & \begin{matrix} 1 & 2 \end{matrix} & 3 \\
4 & \begin{matrix} 5 & 6 \end{matrix} & 7 \\
8 & \color{red}{\begin{matrix} 9 & 10 \end{matrix}} & 11
\end{pmatrix}
$$

**5 min, let's go!**

```{pyodide-python}

```

```{pyodide-python}
M = array([[0, 1, 2, 3],
           [4, 5, 6, 7],
           [8, 9, 10, 11]])

A = M[:-1, 1:]
print(A)
print(A.shape)
print(A.ndim)

B = M[2,1:3]
print(B)
print(B.shape)
print(B.ndim)
```

```{pyodide-python}
M = array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])
M1 = M[0:2,1:4]
print(M1)
print(M1.ndim)

M2 = M[2,1:3]
print(M2)
print(M2.ndim)
```

## Altering a matrix

You may alter a matrix using slices and direct access.
```python
M[2, 3] = 2  # don't use M[2][3] = 2
M[2, :] = some_vector
M[1:3, :] = some_matrix
M[1:4; 2:5] = some_matrix
``` 
The matrices and vectors above **must have the right size** to "fit" in the matrix $M$.

## Reshaping

From a given tensor (vector or matrix or higher dimension tensor) one may obtain a new tensor by **reshaping**.

```{pyodide-python}
A = arange(12)
print(A)
```

```{pyodide-python}
A1 = A.reshape( (3, 4) )
print(A1)

v = A1.reshape( 12 )
print(v)

A2 = A1.reshape( (2,6))
print(A2)
```

```{pyodide-python}
# A2 = A.reshape(2, 3) # error
```

## Reshaping trick

Python can guess one of the dimensions. Give a negative index for the dimension to be guessed.

```{pyodide-python}
A = arange(12)
print(A)
```

```{pyodide-python}
A1 = A.reshape(4, -1)
print(A1)
```

```{pyodide-python}
# A2 = A.reshape(5, -1) # error
```

## Changing the diagonal 

For some applications it might be useful to change the diagonal only. This can be done with the **numpy** function **diag_indices**.

```{pyodide-python}
from numpy import diag_indices
A = zeros(16)
B = A.reshape(4,4)
# print(B)

diagonal = diag_indices(B.shape[0])
print( type(diagonal))
# change the diagonal
B[ diagonal ] = 1.
print(B)
B[:,:] = 0.

for i in range(B.shape[0]):
    B[ i ,i ] = 1.0
        
print(B)
```

```{pyodide-python}
A = arange(16)
B = A.reshape(4,4)

C = zeros( (4,4))
print(C)
for i in range(B.shape[0]): # for all rows
    C[i, :i+1] = B[i,:i+1]

print(C)    
v = zeros( 3 )
for i in range(len(v)): # for entries
    v[i] = B[i,i+1]
 
print(B)
print(v)
```

## Building matrices

- `hstack` to stack matrices **h**orizontally
- `vstack` to stack matrices **v**ertically
- `column_stack` to stack vectors in **columns**

```{pyodide-python}
v0 = array([1, 2])
v1 = array([3, 4])

M0 = hstack([v0,v1])        # the argument is a list of vectors
M1 = vstack([v0, v1])       
M2 = column_stack([v0, v1]) 

print(M0,'\n')
print(M1,'\n')
print(M2)
```

## Methods `sum()`, `max()`, `min()`

```{pyodide-python}
A = array([[1, 2, 3, 4],[5, 6, 7, 8]])
a_sum = A.sum()
a_max = A.max()
row_max = A[0].max()

print(A,'\n')
print("sum =", a_sum)
print("maximum of A =", a_max)
print("maximum of first row =", row_max)
```

# Boolean arrays

```{pyodide-python}
B1 = array([[True, False],
           [False, True]])
print(B1,'\n')

B2 = full((3, 4), False)
print(B2)
```

## Using Boolean arrays

One may use Boolean arrays to create a `template` for modifying another array:

```{pyodide-python}
B = array([[True, False], 
           [False, True]])   # the template array

M = array([[2, 3],
           [1, 4]])    # the other array

M[B] = 0 # using the template
print(M, "\n")

M[B] = 10, 20
print(M)
```

## Creating  Boolean arrays

A comparison operator operating on an array, will create a Boolean array.

```{pyodide-python}
M = array([[2, 3],
           [1, 4]]) 
B1 = M > 2
B2 = M == 4
print(B1,'\n')
print(B2)
```

## Creating and using Boolean arrays

```{pyodide-python}
M = array([[2, 3],
           [1, 4]]) 
B1 = M > 2  # creating a template
M[B1] = 0   # using the template
print(M)
```

We don't have to create a template variable:

```{pyodide-python}
M = array([[2, 3],
           [1, 4]]) 

M[M>2] = 0    # creating a template and using it
print(M)
```

## Comparing arrays

```{pyodide-python}
M1 = array([[2, 3],
            [1, 4]]) 
M2 = array([[0, 5],
            [2, 3]])

B = M2 < M1
print(B,'\n')

C = M2 == M1
print(C)
```

## Array equality

Because array comparisons create Boolean arrays, we need some method for checking equality. We can use the methods `all` or `any`.

```{pyodide-python}
A = array([[1,2],[3,4]])
B = array([[1,2],[3,3]])

equal1 = (A == B).all()
equal2 = (A != B).any()

print("equal1 =", equal1)
print("equal2 =", equal2)
```

## Boolean operators for arrays

We cannot use `and`,`or`, `not`, for Boolean arrays. Instead we use following operators:

- and: `A & B`
- or: &nbsp;  `A | B`
- not: `~A` &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  (the tilde symbol)

```{pyodide-python}
a = array([True, True, False, False]) 
b = array([True, False, True, False])

print(a & b)
print(a | b)
print(~a)
```

# Universal functions

### Definition
A universal function (or `ufunc`) is a function that operates on arrays in an **element-by-element** fashion. That is, a ufunc is a `vectorized` wrapper for a function that takes a fixed number of scalar inputs and produces a fixed number of scalar outputs.

### Example

```{pyodide-python}
x = arange(0, 2*pi, pi/2)
y = sin(x) # the numpy function sin is a ufunc
print(x)
print(y)
```

## Vectorized functions

Non-universal functions can be wrapped to behave like universal functions. This is done by the command `vectorize`.

```{pyodide-python}
# A non-universal function
def const(x):
    return 1

x = linspace(-1, 1, 100)
y1 = const(x)
print("y1 =", y1)

vconst = vectorize(const)
y2 = vconst(x)
print(type(y2))
plot(x, y2)
```

## Another vectorised example

```{pyodide-python}
# A non-universal function
@vectorize
def heaviside(x): # named after Oliver Heaviside
    if x >= 0:
        return 1
    else:
        return 0

x = linspace(-1, 1, 100)
plot(x, heaviside(x))    # note: the plot is not correct
```

# Images as matrices

For demonstration purposes, we can use an image of a racoon provided by scipy.

```{pyodide-python}
import scipy.misc
M = scipy.datasets.face(gray = True)  # for starters, use a gray scale
print("M:", type(M))
print("M.shape =", M.shape)
print("dtype =", M.dtype)
imshow(M, cmap='gray')   # use a gray scale color map (cmap)
```

## Arithmetic operations

```{pyodide-python}
M = scipy.datasets.face(gray = True)
M1 = 255-M            # negative image
M2 = (M/255)**2*255   # quadratic function

figure(figsize=(12, 4)) # 12 inches wide and 4 inches high
subplot(131)
imshow(M, cmap='gray')
subplot(132)
imshow(M1, cmap='gray')
subplot(133)
imshow(M2, cmap='gray', vmin = 0, vmax = 255)
```

## Slices

```{pyodide-python}
M = scipy.datasets.face(gray = True)
M1 = M[400:600, :]
M2 = M[:600, 600: ]

figure(figsize=(12, 4))
subplot(131)
imshow(M, cmap='gray')
subplot(132)
imshow(M1, cmap='gray')
subplot(133)
imshow(M2, cmap='gray')
```

## Boolean arrays

```{pyodide-python}
figure(figsize=(12, 4))
M = scipy.datasets.face(gray = True)
subplot(131)
imshow(M, cmap='gray')

M[M>127] = 255
subplot(132)
imshow(M, cmap='gray')

M[M<=127] = 0
subplot(133)
imshow(M, cmap='gray')
```

## RGB images

```{pyodide-python}
M = scipy.datasets.face()
print("M.shape =", M.shape)
print("M.ndim =", M.ndim)
print("dtype =", M.dtype)
print("M[0, 0] =", M[0, 0])

imshow(M)
```

## Slices

```{pyodide-python}
M = scipy.datasets.face().copy()  # must make a copy to change it

figure(figsize=(12, 4))
subplot(131)
imshow(M)

M[:, :, 0] = 255  # maximize red for each pixels
subplot(132)
imshow(M)

#                       R  G   B
M[100: 200, 100:800] = [0, 0, 255]  # make a blue rectangle  
# try RGB with programs like gimp or inkscape
subplot(133)
imshow(M)
```

## Comparison and Boolean operators

```{pyodide-python}
M = scipy.datasets.face().copy()  # must make a copy to change it

figure(figsize=(8, 4))
subplot(121)
imshow(M)

# [ R, G, B]
g_larger_than_r = M[:, :, 1] > M[:, :, 0]
g_larger_than_b = M[:, :, 1] > M[:, :, 2]
g_larger_than_both = g_larger_than_r & g_larger_than_b
print(M.shape)
print(g_larger_than_both.shape)

M[g_larger_than_both, 1] = 0  # remove green from mostly green pixels
subplot(122)
imshow(M)
```

## Other images

Use Python Image Library, PIL.

> Note: The code below is only necessary in the browser/Pyodide environment, where the image file may not be stored in the local filesystem. In a normal Python interpreter you can use the same code when the file exists locally.

```{pyodide-python}
import os
import io
from js import fetch, Uint8Array
from PIL import Image
from numpy import *
from matplotlib.pyplot import *

async def read_image(path):
    if os.path.exists(path):
        return Image.open(path)
    response = await fetch(path)
    array_buffer = await response.arrayBuffer()
    data = Uint8Array.new(array_buffer).to_py()
    return Image.open(io.BytesIO(data))

img = await read_image("MonaLisa.jpg")
ML = array(img)  # make a numpy array that can be manipulated
print(ML.shape)
imshow(ML)
plt.show()
```

Normal Python reference:

```python
from PIL import Image
img = Image.open("MonaLisa.jpg")
ML = array(img)
print(ML.shape)
```

### Exercise: Try this with an image of your choice!

<nav class="bottom-page-nav" aria-label="Page navigation">
  <a class="page-nav-link prev" href="lecture06.html">Previous: Lecture 6</a>
  <a class="page-nav-link next" href="lecture08.html">Next: Lecture 8</a>
</nav>
